# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38a206edf49e32426fc9f2d464ac9fe7"
name = "shop-chat-agent"
handle = "shop-chat-agent-715"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_cr













edit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
